spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  config:
    import:
      - classpath:config/kafka.yml
app:
  application:
    name: hr-service

management:
  endpoints:
    web:
      exposure:
        include: health,info